# SuperVanish v5.8.3 - Configuration
#
Configuration:
##################################################
################ MESSAGE OPTIONS #################
##################################################
  Messages:
    ####### Fake Join-/LeaveMessages #######
    VanishReappearMessages:
      # Should this plugin broadcast a message when a player vanishs?
      # You can change that message in the messages.yml file.
      BroadcastMessageOnVanish: true
      # Should this plugin broadcast a message when a player reappears?
      # You can change that message in the messages.yml file.
      BroadcastMessageOnReappear: true
      # Should players with the permission 'sv.see' get an other message when a player vanishs/reappears?
      # You can change that message in the messages.yml file.
      SendDifferentMessages: true
      # Should only players with the permission 'sv.see' receive 'fake' Join-/LeaveMessages?
      SendMessageOnlyToAdmins: false
      # Should only players without the permission 'sv.see' receive 'fake' Join-/LeaveMessages?
      SendMessageOnlyToUsers: false
    ########################################
    # Should this plugin hide the 'normal' Join- and LeaveMessages of invisible players?
    HideNormalJoinAndLeaveMessagesWhileInvisible: true
    # Should this plugin remind players who join the server invisible?
    # You can change that message in the messages.yml file.
    RemindInvisiblePlayersOnJoin: true
    # Should invisible players have action bars that tell them that they're invisible?
    # You can change the actionbar msg in the messages.yml file.
    DisplayActionBarsToInvisiblePlayers: true
##################################################
################ PLAYER OPTIONS ##################
##################################################
  Players:
    # Should invisible players be able to pick up items?
    DisableItemPickUpsByDefault: true
    # Should invisible players have the night vision effect?
    AddNightVision: true
    # Should this plugin disable hunger of invisible players?
    DisableHungerForInvisiblePlayers: true
    ################## FLY #################
    Fly:
      # Should invisible players be able to fly even if they aren't in creative mode?
      Enable: true
      # Should invisible players WITHOUT the permission 'sv.fly' lose the ability to fly on reappear?
      DisableOnReappear: true
    ########################################
    # Should invisible players not be able to trigger pressure plates and tripwire?
    # If this feature is enabled invisible players can't trigger pressure plates and tripwire.
    DisablePressurePlatesForInvisiblePlayers: true
    # Should players with the permission 'sv.see' be able to see invisible players?
    EnableSeePermission: true
    # Should invisible players not be able to break blocks?
    PreventBlockBreaking: false
    # Should invisible players not be able to place blocks?
    PreventBlockPlacing: false
    # Should invisible players not be able to damage players or mobs?
    PreventHittingEntities: false
    # Should invisible players open chests without the chest animation and sounds? Requires ProtocolLib.
    SilentOpenChest: true
    # Should invisible players automatically reappear when they change their world?
    ReappearOnWorldChange: false
    # Should invisible players automatically reappear when they quit the server?
    ReappearOnQuit: false
    # Should SV still handle leave messages if 'ReappearOnQuit' is turned on?
    ReappearOnQuitHandleLeaveMsg: true
    # Should invisible players not be able to push other players or be able to be pushed?
    # Uses the scoreboard and may conflict with other plugins; Ignored in 1.8 or below
    DisablePush: true
##################################################
################ TABLIST OPTIONS #################
##################################################
  Tablist:
    # Should invisible players have a prefix in the tablist and on their nametag?
    # (shows up for players with the permission 'sv.see' if it is enabled)
    # You can use color codes here; please make sure that the prefix isn't longer than 16 characters
    # Uses the scoreboard and may conflict with other plugins
    TabPrefix: ""
    # Should invisible players have a suffix in the tablist and on their nametag?
    # (shows up for players with the permission 'sv.see' if it is enabled)
    # You can use color codes here; please make sure that the suffix isn't longer than 16 characters
    # Uses the scoreboard and may conflict with other plugins
    TabSuffix: " &a[HIDDEN]"
##################################################
############## SERVERLIST OPTIONS ################
##################################################
  Serverlist:
    # !! PLEASE TURN THE NEXT TWO SETTINGS OFF IF YOU ARE RUNNING BUNGEECORD !!
    # The server list features require the plugin ProtocolLib and don't support BungeeCord!
    # Should this plugin adjust the amount of players in the server list?
    AdjustAmountOfOnlinePlayers: true
    # Should this plugin hide invisible players in the list of logged-in players?
    # You can view this list when your mouse hovers over the amount of online players.
    AdjustListOfLoggedInPlayers: true
##################################################
################## HOOK OPTIONS ##################
##################################################
  Hooks:
    # Should SV hide invisible players in /who, /list, /online
    # and all other commands of Essentials?
    # Note: Players with a specific Essentials permission can still see invisible players in those commands
    # Important: You have to reload both Essentials and SuperVanish if you change this setting.
    EnableEssentialsHook: true
    # Should SV hide invisible players on your dynamic map?
    EnableDynmapHook: true
    DynmapHook:
      # Should SV and broadcast join/leave messages if you use enabled Dynmap hook?
      ShowJoinQuitMessage: true
    # Should SV prevent players from being invisible and disguised at the same time? (LibsDisguises commands)
    # It's recommended to keep this turned on to prevent incompatibility.
    EnableLibsDisguisesHook: true
    # Should SV prevent players from being invisible and disguised at the same time? (DisguiseCraft commands)
    # It's recommended to keep this turned on to prevent incompatibility.
    EnableDisguiseCraftHook: true
    # Should SV hook into TraiGUI and disable trails for vanished players?
    EnableTrailGUIHook: true
    # Should SV hook into SuperTrails and disable trails for vanished players?
    EnableSuperTrailsHook: true
    # Should SV stop NPCs from greeting or talking about hidden players?
    EnableCitizensHook: true
    # Should SV hide invisible players on Enjin's website?
    EnableEnjinMinecraftPluginHook: true
##################################################
############# COMPATIBILITY OPTIONS ##############
##################################################
  CompatibilityOptions:
    # The event priority which supervanish should use for the specific event.
    # If another plugin overrides supervanish's join/leave settings, setting the priorities to MONITOR can help.
    # Allowed values: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
    PlayerJoinEventPriority: HIGH # <- Set this to "HIGH" if you use Essentials to modify join messages
    PlayerQuitEventPriority: HIGHEST
#################################################
################# DO NOT TOUCH ##################
#################################################
ConfigVersion: 5.8.3